name: 部署到 GitHub Pages

on:
  # 推送到 main 分支时触发
  push:
    branches: [ main ]
  
  # 手动触发
  workflow_dispatch:

# 设置 GITHUB_TOKEN 权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，跳过正在进行的运行之间排队的运行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建作业
  build:
    name: 构建
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 缓存 Bun 依赖
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: 安装依赖
        run: bun install

      - name: 运行测试
        run: bun test

    #   - name: 代码检查
    #     run: bun lint

      - name: 构建项目
        run: bun run build:gh-pages
        env:
          NODE_ENV: production

      - name: 设置 Pages
        uses: actions/configure-pages@v4

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  # 部署作业
  deploy:
    name: 部署
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
